steps:
  # Install pnpm globally
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g pnpm

  # Install dependencies using pnpm
  - name: 'node:18'
    entrypoint: 'pnpm'
    args: ['install']

  # Build the application
  - name: 'node:18'
    entrypoint: 'pnpm'
    args: ['build']

  # Deploy to Cloud Run (or other service)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'nilo-temp-app', '--image', 'gcr.io/nilo-temp/dunty', '--region', 'us-central1']

timeout: '1800s' # Extend timeout if needed
