declare function Linear(x: number): number;
declare function InSine(x: number): number;
declare function OutSine(x: number): number;
declare function InOutSine(x: number): number;
declare function InQuad(x: number): number;
declare function OutQuad(x: number): number;
declare function InOutQuad(x: number): number;
declare function InCubic(x: number): number;
declare function OutCubic(x: number): number;
declare function InOutCubic(x: number): number;
declare function InQuart(x: number): number;
declare function OutQuart(x: number): number;
declare function InOutQuart(x: number): number;
declare function InQuint(x: number): number;
declare function OutQuint(x: number): number;
declare function InOutQuint(x: number): number;
declare function InExpo(x: number): number;
declare function OutExpo(x: number): number;
declare function InOutExpo(x: number): number;
declare function InCirc(x: number): number;
declare function OutCirc(x: number): number;
declare function InOutCirc(x: number): number;
declare function InBack(x: number): number;
declare function OutBack(x: number): number;
declare function InOutBack(x: number): number;
declare function InElastic(x: number): number;
declare function OutElastic(x: number): number;
declare function InOutElastic(x: number): number;
declare function InBounce(x: number): number;
declare function OutBounce(x: number): number;
declare function InOutBounce(x: number): number;
export declare const Ease: {
    Linear: typeof Linear;
    InSine: typeof InSine;
    OutSine: typeof OutSine;
    InOutSine: typeof InOutSine;
    InQuad: typeof InQuad;
    OutQuad: typeof OutQuad;
    InOutQuad: typeof InOutQuad;
    InCubic: typeof InCubic;
    OutCubic: typeof OutCubic;
    InOutCubic: typeof InOutCubic;
    InQuart: typeof InQuart;
    OutQuart: typeof OutQuart;
    InOutQuart: typeof InOutQuart;
    InQuint: typeof InQuint;
    OutQuint: typeof OutQuint;
    InOutQuint: typeof InOutQuint;
    InExpo: typeof InExpo;
    OutExpo: typeof OutExpo;
    InOutExpo: typeof InOutExpo;
    InCirc: typeof InCirc;
    OutCirc: typeof OutCirc;
    InOutCirc: typeof InOutCirc;
    InBack: typeof InBack;
    OutBack: typeof OutBack;
    InOutBack: typeof InOutBack;
    InElastic: typeof InElastic;
    OutElastic: typeof OutElastic;
    InOutElastic: typeof InOutElastic;
    InBounce: typeof InBounce;
    OutBounce: typeof OutBounce;
    InOutBounce: typeof InOutBounce;
};
export {};
